name: Feature Request
description: Propose a new feature or idea.
title: "[FEATURE]: "
labels: ["enhancement"]
body:
  - type: markdown
    attributes:
      value: |
        Share your feature ideas. One issue per feature.

  - type: textarea
    id: problem
    attributes:
      label: What problem would this solve?
      description: Describe the problem this solves.
      placeholder: For example, setting X currently requires too many manual steps.
    validations:
      required: true

  - type: textarea
    id: solution
    attributes:
      label: Proposed Solution
      description: Describe the proposed feature.
      placeholder: I would like a new button in menu Y that automates Z.
    validations:
      required: true

  - type: textarea
    id: alternatives
    attributes:
      label: Alternatives Considered
      description: Did you consider other approaches?
    validations:
      required: false

  - type: textarea
    id: context
    attributes:
      label: Additional Context
      description: Add screenshots or links.
    validations:
      required: false

  - type: checkboxes
    id: logic-check
    attributes:
      label: Contribution Agreement
      options:
        - label: I understand that this proposal will be evaluated against the current project roadmap.
          required: true
